In [21]:
import numpy as np


In [83]:
def simple_conv2d(input_matrix: np.ndarray, kernel: np.ndarray, padding: int, stride: int):
    input_height, input_width = input_matrix.shape
    kernel_height, kernel_width = kernel.shape
    padded_matrix = np.pad(input_matrix, ((padding, padding), (padding, padding)), mode='constant')
    res_h= ((input_height+padding*2-kernel_height)//stride) +1
    res_w= ((input_width+padding*2-kernel_width)//stride) +1
    result_matrix = np.zeros((res_h, res_w))
    padded_matrix_height, padded_matrix_width = padded_matrix.shape

    for i in range(0, padded_matrix_height-kernel_height+1, stride):
        for j in range(0, padded_matrix_width-kernel_width+1, stride):
            result_matrix[i//stride, j//stride] = np.sum(padded_matrix[i:i+kernel_height, j:j+kernel_width] * kernel)
    return result_matrix


In [73]:
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 2

In [84]:

output = simple_conv2d(input_matrix, kernel, padding, stride)
print(output)

[[ 1.  1. -4.]
 [ 9.  7. -4.]
 [ 0. 14. 16.]]


In [85]:
input_matrix = np.array([ [1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.], [11., 12., 13., 14., 15.], [16., 17., 18., 19., 20.], [21., 22., 23., 24., 25.], ]) 
kernel = np.array([ [.5, 3.2], [1., -1.], ]) 
padding, stride = 2, 2

output = simple_conv2d(input_matrix, kernel, padding, stride)
output

array([[ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  5.9, 13.3, 12.5],
       [ 0. , 42.9, 50.3, 27.5],
       [ 0. , 80.9, 88.3, 12.5]])