In [42]:
import numpy as np 

In [43]:
# https://fr.wikipedia.org/wiki/D%C3%A9composition_en_valeurs_singuli%C3%A8res
# Le théorème spectral énonce qu'une matrice normale peut être diagonalisée par une base orthonormée de vecteurs propres. 
# On peut voir la décomposition en valeurs singulières comme une généralisation du théorème spectral à des matrices arbitraires, qui ne sont pas nécessairement carrées.

In [44]:

def compute_eigenvalues(matrix):
    """
    Compute the eigenvalues of a given square matrix.
    
    Parameters:
    matrix (numpy.ndarray): A square matrix of size n x n.
    
    Returns:
    numpy.ndarray: The eigenvalues of the matrix.
    """
    if not isinstance(matrix, np.ndarray):
        raise ValueError("Input must be a numpy array.")
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Input must be a square matrix.")
    
    # Compute eigenvalues using numpy's eigvals function
    eigenvalues = np.linalg.eigvals(matrix)
    return eigenvalues

def svd_2x2_singular_values(A: np.ndarray) -> tuple:
    # Compute Gramian matrix
    gramian_matrix = np.dot(A.T, A)

    # Use eigh for symmetric matrices (more stable)
    eigenvalues, eigenvectors = np.linalg.eigh(gramian_matrix)

    # Sort eigenvalues and eigenvectors in descending order
    idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]

    # Compute singular values
    sigma1, sigma2 = np.sqrt(eigenvalues)

    # Right singular vectors (columns of V)
    v1 = eigenvectors[:, 0]
    v2 = eigenvectors[:, 1]
    V = np.column_stack((v1, v2))

    # Left singular vectors (U)
    u1 = A @ v1
    if sigma1 > 1e-10:
        u1 /= sigma1
    else:
        u1[:] = 0

    u2 = A @ v2
    if sigma2 > 1e-10:
        u2 /= sigma2
    else:
        u2[:] = 0

    U = np.column_stack((u1, u2))

    # Ensure U is orthonormal (optional orthonormalization step)
    U, _ = np.linalg.qr(U)

    # Diagonal matrix of singular values
    Sigma = np.diag([sigma1, sigma2])

    return U, Sigma, V.T

In [45]:
a = np.array([[2, 1], [1, 2]])
U, Sigma, V = svd_2x2_singular_values(a)
print(U)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [46]:
#print the values in the diagonal of the sigma matrix
import numpy as np
print(Sigma)

[[3. 0.]
 [0. 1.]]


In [47]:
print(U, Sigma, V)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] [[3. 0.]
 [0. 1.]] [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
