In [1]:
import numpy as np


In [2]:
def make_diagonal(x):
    n = len(x)
    output = np.zeros((n, n))
    for i in range(n):
        output[i, i] = x[i]
    return output


In [3]:
x = np.array([1, 2, 3])
output = make_diagonal(x)
print(output)


[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
