In [32]:
import numpy as np 
np.random.seed(42)

In [39]:

def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    """
    Implement k-fold cross-validation by returning train-test indices.
    """
    assert k > 1, "k must be greater than 1"
    assert X.shape[0] == y.shape[0], "X and y must have the same number of samples"

    fold_size= X.shape[0]//k
    folds = []
    if shuffle:
        X = np.random.permutation(X)
    for i in range(k):
        folds.append(X[i*fold_size:(i+1)*fold_size])
    datasets = []
    for i in range(k):
        test_fold = folds[i]
        train_folds = [fold for j, fold in enumerate(folds) if j != i]
        train_data = np.concatenate(train_folds)
        datasets.append((train_data, test_fold))
    return datasets

In [34]:
k_fold_cross_validation(np.array([0,1,2,3,4,5,6,7,8,9]), np.array([0,1,2,3,4,5,6,7,8,9]), k=5, shuffle=False)

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [44]:
matrix= [[1, 0, 0], 
             [0, 1, 0], 
             [0, 0, 1]]
matrix[1:]

[[0, 1, 0], [0, 0, 1]]